# Generated by ./dev.sh brew from packaging/homebrew/macremote.rb.in
class Macremote < Formula
  desc "Your Mac's terminals, files and Claude Code sessions on your phone"
  homepage "https://github.com/babakzarrinbal/homebrew-macremote"
  version "2026.10.01"

  on_macos do
    on_arm do
      url "https://github.com/babakzarrinbal/homebrew-macremote/releases/download/v2026.10.01/macremote-2026.10.01-darwin-arm64.tar.gz"
      sha256 "a78f41e2bb7318099773c811f14058448f5b2c442b2ac000fbaeff2337db4fa9"
    end
    on_intel do
      url "https://github.com/babakzarrinbal/homebrew-macremote/releases/download/v2026.10.01/macremote-2026.10.01-darwin-amd64.tar.gz"
      sha256 "62118c8f595a9ab6ffd3bb10e3933a09251511c78eebdddb5b4413a9c90e4a70"
    end
  end
  depends_on :macos

  def install
    bin.install "macremote"
  end

  service do
    run [opt_bin/"macremote", "serve"]
    keep_alive true
    process_type :interactive
    log_path var/"log/macremote.log"
    error_log_path var/"log/macremote.log"
  end

  def caveats
    <<~EOS
      Run it now and at every login:
        brew services start macremote
      Then pair your phone: run `macremote pair` and scan the code
      with the Mac Remote app.

      Installed it before with install.sh? Run `macremote uninstall` first,
      so only one copy runs (your paired phones are kept).
    EOS
  end

  test do
    assert_match "usage: macremote", shell_output("#{bin}/macremote 2>&1", 2)
  end
end
