# Generated by ./dev.sh brew from packaging/homebrew/macremote.rb.in
class Macremote < Formula
  desc "Your Mac's terminals, files and Claude Code sessions on your phone"
  homepage "https://github.com/babakzarrinbal/homebrew-macremote"
  version "2026.10.01.2"

  on_macos do
    on_arm do
      url "https://github.com/babakzarrinbal/homebrew-macremote/releases/download/v2026.10.01.2/macremote-2026.10.01.2-darwin-arm64.tar.gz"
      sha256 "776b5dd0eb2648fc71d3e2a9ca55bb0cc6aa684fd8fb1a74d14d436ce27d7ea9"
    end
    on_intel do
      url "https://github.com/babakzarrinbal/homebrew-macremote/releases/download/v2026.10.01.2/macremote-2026.10.01.2-darwin-amd64.tar.gz"
      sha256 "31a99e821cd8a4c8af06a2d04b74d4b51ca25d5181977c08af9c7693f53094fb"
    end
  end
  depends_on :macos

  def install
    bin.install "macremote"
  end

  service do
    run [opt_bin/"macremote", "serve"]
    keep_alive true
    process_type :interactive
    log_path var/"log/macremote.log"
    error_log_path var/"log/macremote.log"
  end

  def caveats
    <<~EOS
      Point it at your relay; this starts it (now and at every login)
      and shows a code to scan with the Mac Remote app:
        macremote setup your.server:8460

      It shows the relay's certificate pin to compare with
      `docker exec macremote-relay /relay pin` on the server
      (or pass it: -pin <sha256>). More phones later: macremote pair.

      Installed it before with install.sh? Run `macremote uninstall` first,
      so only one copy runs (your paired phones are kept).
    EOS
  end

  test do
    assert_match "usage: macremote", shell_output("#{bin}/macremote 2>&1", 2)
  end
end
